#!/bin/bash
#----------------------------------------------------
# Sample Slurm job script
#   for TACC Stampede2 KNL nodes
#
#   *** MPI Job on Normal Queue ***
#
# Last revised: 20 Oct 2017
#
# Notes:
#
#   -- Launch this script by executing
#      "sbatch file_name.slurm" on Stampede2 login node.
#
#   -- Use ibrun to launch MPI codes on TACC systems.
#      Do not use mpirun or mpiexec.
#
#   -- Max recommended MPI tasks per KNL node: 64-68
#      (start small, increase gradually).
#
#   -- If you're running out of memory, try running
#      fewer tasks per node to give each task more memory.
#
#----------------------------------------------------

#SBATCH -J         airline_with_comm_N_Node=32_particles=20_expn=0     # Job name
#SBATCH -o exp_out/airline_with_comm_N_Node=32_particles=20_expn=0.o%j # Name of stdout output file
#SBATCH -e exp_err/airline_with_comm_N_Node=32_particles=20_expn=0.e%j # Name of stderr error file
#SBATCH -p normal                                                # Queue (partition) name
#SBATCH -N 1                                                     # Total # of nodes
#SBATCH -n 32                                                    # Total # of mpi tasks
#SBATCH -t 48:00:00                                              # Run time (hh:mm:ss)
#SBATCH --mail-user=ochavez@utexas.edu
#SBATCH --mail-type=all                                          # Send email at begin and end of job

# Other commands must follow all #SBATCH directives...

#module list
#pwd
#date

# Launch MPI code...
# Use ibrun instead of mpirun or mpiexec
ibrun python mpi_emb_par_sim_dat_with_comm.py  --Xy_N 1000 --Epoch_N 100 --Nt 20 --p 76 --N_Node 32 --particles_per_shard 20 --experiment_number 0 --save_history 0 --GP_version 0 --randomize_shards 0 --files_to_process_path HENSMAN_file_name_stems --results_sub_folder airline_data --source_folder data --communicate 1
