#!/bin/bash
#----------------------------------------------------
# Sample Slurm job script
#   for TACC Stampede2 KNL nodes
#
#   *** MPI Job on Normal Queue ***
#
# Last revised: 20 Oct 2017
#
# Notes:
#
#   -- Launch this script by executing
#      "sbatch file_name.slurm" on Stampede2 login node.
#
#   -- Use ibrun to launch MPI codes on TACC systems.
#      Do not use mpirun or mpiexec.
#
#   -- Max recommended MPI tasks per KNL node: 64-68
#      (start small, increase gradually).
#
#   -- If you're running out of memory, try running
#      fewer tasks per node to give each task more memory.
#
#----------------------------------------------------

#SBATCH -J         Xy_N=6000_Epoch_N=600_N_Node=60_p=8_particles=1000_expn=0     # Job name
#SBATCH -o exp_out/Xy_N=6000_Epoch_N=600_N_Node=60_p=8_particles=1000_expn=0.o%j # Name of stdout output file
#SBATCH -e exp_err/Xy_N=6000_Epoch_N=600_N_Node=60_p=8_particles=1000_expn=0.e%j # Name of stderr error file
#SBATCH -p normal                                                # Queue (partition) name
#SBATCH -N 1                                                     # Total # of nodes
#SBATCH -n 60                                                    # Total # of mpi tasks
#SBATCH -t 48:00:00                                              # Run time (hh:mm:ss)
#SBATCH --mail-user=ochavez@utexas.edu
#SBATCH --mail-type=all                                          # Send email at begin and end of job

# Other commands must follow all #SBATCH directives...

#module list
#pwd
#date

# Launch MPI code...
# Use ibrun instead of mpirun or mpiexec

ibrun python mpi_emb_par_sim_dat_with_comm.py --Xy_N 6000 --Epoch_N 600 --N_Node 60 --Nt 30 --p 8 --particles_per_shard 1000 --experiment_number 0 --GP_version 0 --save_history 1 --randomize_shards 1 
ibrun   python mpi_emb_par_sim_dat_no_comm.py --Xy_N 6000 --Epoch_N 600 --N_Node 60 --Nt 30 --p 8 --particles_per_shard 1000 --experiment_number 0 --GP_version 0 --save_history 1 --randomize_shards 1 
ibrun python mpi_emb_par_sim_dat_with_comm.py --Xy_N 6000 --Epoch_N 600 --N_Node 60 --Nt 30 --p 8 --particles_per_shard 1000 --experiment_number 0 --GP_version 1 --save_history 1 --randomize_shards 1 
ibrun   python mpi_emb_par_sim_dat_no_comm.py --Xy_N 6000 --Epoch_N 600 --N_Node 60 --Nt 30 --p 8 --particles_per_shard 1000 --experiment_number 0 --GP_version 1 --save_history 1 --randomize_shards 1 
ibrun python mpi_emb_par_sim_dat_with_comm.py --Xy_N 6000 --Epoch_N 600 --N_Node 60 --Nt 30 --p 8 --particles_per_shard 1000 --experiment_number 0 --GP_version 2 --save_history 1 --randomize_shards 1 
ibrun   python mpi_emb_par_sim_dat_no_comm.py --Xy_N 6000 --Epoch_N 600 --N_Node 60 --Nt 30 --p 8 --particles_per_shard 1000 --experiment_number 0 --GP_version 2 --save_history 1 --randomize_shards 1 
ibrun python mpi_emb_par_sim_dat_with_comm.py --Xy_N 6000 --Epoch_N 600 --N_Node 60 --Nt 30 --p 8 --particles_per_shard 1000 --experiment_number 0 --GP_version 3 --save_history 1 --randomize_shards 1 
ibrun   python mpi_emb_par_sim_dat_no_comm.py --Xy_N 6000 --Epoch_N 600 --N_Node 60 --Nt 30 --p 8 --particles_per_shard 1000 --experiment_number 0 --GP_version 3 --save_history 1 --randomize_shards 1 
ibrun python mpi_emb_par_sim_dat_with_comm.py --Xy_N 6000 --Epoch_N 600 --N_Node 60 --Nt 30 --p 8 --particles_per_shard 1000 --experiment_number 0 --GP_version 4 --save_history 1 --randomize_shards 1 
ibrun   python mpi_emb_par_sim_dat_no_comm.py --Xy_N 6000 --Epoch_N 600 --N_Node 60 --Nt 30 --p 8 --particles_per_shard 1000 --experiment_number 0 --GP_version 4 --save_history 1 --randomize_shards 1 
ibrun python mpi_emb_par_sim_dat_with_comm.py --Xy_N 6000 --Epoch_N 600 --N_Node 60 --Nt 30 --p 8 --particles_per_shard 1000 --experiment_number 0 --GP_version 5 --save_history 1 --randomize_shards 1 
ibrun   python mpi_emb_par_sim_dat_no_comm.py --Xy_N 6000 --Epoch_N 600 --N_Node 60 --Nt 30 --p 8 --particles_per_shard 1000 --experiment_number 0 --GP_version 5 --save_history 1 --randomize_shards 1 
ibrun python mpi_emb_par_sim_dat_with_comm.py --Xy_N 6000 --Epoch_N 600 --N_Node 60 --Nt 30 --p 8 --particles_per_shard 1000 --experiment_number 0 --GP_version 6 --save_history 1 --randomize_shards 1 
ibrun   python mpi_emb_par_sim_dat_no_comm.py --Xy_N 6000 --Epoch_N 600 --N_Node 60 --Nt 30 --p 8 --particles_per_shard 1000 --experiment_number 0 --GP_version 6 --save_history 1 --randomize_shards 1 
ibrun python mpi_emb_par_sim_dat_with_comm.py --Xy_N 6000 --Epoch_N 600 --N_Node 60 --Nt 30 --p 8 --particles_per_shard 1000 --experiment_number 0 --GP_version 7 --save_history 1 --randomize_shards 1 
ibrun   python mpi_emb_par_sim_dat_no_comm.py --Xy_N 6000 --Epoch_N 600 --N_Node 60 --Nt 30 --p 8 --particles_per_shard 1000 --experiment_number 0 --GP_version 7 --save_history 1 --randomize_shards 1 
ibrun python mpi_emb_par_sim_dat_with_comm.py --Xy_N 6000 --Epoch_N 600 --N_Node 60 --Nt 30 --p 8 --particles_per_shard 1000 --experiment_number 0 --GP_version 8 --save_history 1 --randomize_shards 1 
ibrun   python mpi_emb_par_sim_dat_no_comm.py --Xy_N 6000 --Epoch_N 600 --N_Node 60 --Nt 30 --p 8 --particles_per_shard 1000 --experiment_number 0 --GP_version 8 --save_history 1 --randomize_shards 1 
ibrun python mpi_emb_par_sim_dat_with_comm.py --Xy_N 6000 --Epoch_N 600 --N_Node 60 --Nt 30 --p 8 --particles_per_shard 1000 --experiment_number 0 --GP_version 9 --save_history 1 --randomize_shards 1 
ibrun   python mpi_emb_par_sim_dat_no_comm.py --Xy_N 6000 --Epoch_N 600 --N_Node 60 --Nt 30 --p 8 --particles_per_shard 1000 --experiment_number 0 --GP_version 9 --save_history 1 --randomize_shards 1 

# ---------------------------------------------------
