#!/bin/bash
#----------------------------------------------------
# Sample Slurm job script
#   for TACC Stampede2 KNL nodes
#
#   *** MPI Job on Normal Queue ***
#
# Last revised: 20 Oct 2017
#
# Notes:
#
#   -- Launch this script by executing
#      "sbatch file_name.slurm" on Stampede2 login node.
#
#   -- Use ibrun to launch MPI codes on TACC systems.
#      Do not use mpirun or mpiexec.
#
#   -- Max recommended MPI tasks per KNL node: 64-68
#      (start small, increase gradually).
#
#   -- If you're running out of memory, try running
#      fewer tasks per node to give each task more memory.
#
#----------------------------------------------------

#SBATCH -J Xy_N=150000_Epoch_N=100_N_Node=10_expn=7             # Job name
#SBATCH -o exp_out/Xy_N=150000_Epoch_N=100_N_Node=10_expn=1.o%j # Name of stdout output file
#SBATCH -e exp_err/Xy_N=150000_Epoch_N=100_N_Node=10_expn=1.e%j # Name of stderr error file
#SBATCH -p normal                                               # Queue (partition) name
#SBATCH -N 10                                                   # Total # of nodes
#SBATCH -n 10                                                   # Total # of mpi tasks
#SBATCH -t 48:00:00                                             # Run time (hh:mm:ss)
#SBATCH --mail-user=ochavez@utexas.edu
#SBATCH --mail-type=all                    # Send email at begin and end of job

# Other commands must follow all #SBATCH directives...

#module list
#pwd
#date

# Launch MPI code...

ibrun python mpi_emb_par_sim_dat.py --Xy_N 150000 --Epoch_N 100 --N_Node 10 --Nt 10 --p 100 --particles_per_shard 1000 --experiment_number 7      # Use ibrun instead of mpirun or mpiexec

# ---------------------------------------------------
